import {CenterDiv} from "../../const/StyledConst";

const About = () : JSX.Element => {

    return(
        <CenterDiv>
            <h1 className="title">ABOUT</h1>
            <div className="hr"></div>
            진짜 너무 졸린데?
            <div>따라라라</div>
            <div>
            오키오키
            </div>
            <div>
            오키오키
            </div>
            <div>
            오키오키
            </div>
            <div>
            오키오키
            </div>
            <div>
            오키오키
            </div>
            <div>
            오키오키
            </div>
            <div>
            오키오키
            </div>
            <div>
            오키오키
            </div>
            <div>
            오키오키
            </div>
            <div>
            오키오키
            </div>
            <div>
            오키오키
            </div>
            <div>
            오키오키
            </div>
            <div>
            오키오키
            </div>
            <div>
            오키오키
            </div>
            <div>
            오키오키
            </div>
            <div>
            오키오키
            </div>
            <div>
            오키오키
            </div>
            <div>
            오키오키
            </div>
            <div>
            오키오키
            </div>
            <div>
            오키오키
            </div>
            <div>
            오키오키
            </div>
            <div>
            오키오키
            </div>
            <div>
            오키오키
            </div>
            <div>
            오키오키
            </div>
            <div>
            오키오키
            </div>
            <div>
            오키오키
            </div>
            <div>
            오키오키
            </div>
            <div>
            오키오키
            </div>
            <div>
            오키오키
            </div>
            <div>
            오키오키
            </div>
            <div>
            오키오키
            </div>
            <div>
            오키오키
            </div>
            <div>
            오키오키
            </div>
            <div>
            오키오키
            </div>
            <div>
            오키오키
            </div>
            <div>
            오키오키
            </div>
            <div>
            오키오키
            </div>
            <div>
            오키오키
            </div>
            <div>
            오키오키
            </div>
            <div>
            오키오키
            </div>
            <div>
            오키오키
            </div>
            <div>
            오키오키
            </div>
            <div>
            오키오키
            </div>
            <div>
            오키오키
            </div>
            <div>
            오키오키
            </div>
            <div>
            오키오키
            </div>
            <div>
            오키오키
            </div>
            <div>
            오키오키
            </div>
            <div>
            오키오키
            </div>
            <div>
            오키오키
            </div>
            <div>
            오키오키
            </div>
            <div>
            오키오키
            </div>
            
        </CenterDiv>
    
    )
}

export default About;